function Hd = Filter_makeChebyshev(obj,Fpass1,Fpass2)
%FILTER_MAKECHEBYSHEV Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 8.0 and the Signal Processing Toolbox 6.18.
%
% Generated on: 08-Apr-2013 11:28:42
%

% Chebyshev Type I Bandpass filter designed using FDESIGN.BANDPASS.



N      = 10;  % Order
% Fpass1 = 3;   % First Passband Frequency
% Fpass2 = 7;   % Second Passband Frequency
Apass  = 1;   % Passband Ripple (dB)

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.bandpass('N,Fp1,Fp2,Ap', N, Fpass1, Fpass2, Apass, obj.FMCSamplingRate);
Hd = design(h, 'cheby1');

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
obj.filter = dfilt.df2(b, a);



% [EOF]
